name: Patchwork Triage

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    - uses: BluezTestBot/action-patchwork-status@master
      with:
        task: 'triage'
        github_token: ${{ secrets.ACTION_TOKEN }}
        email_token: ${{ secrets.EMAIL_TOKEN }}
        patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}

